config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'
  
  controller :sessions do
    get     'login'   => :new
    post    'login'   => :create
    delete  'logout'  => :destroy
  end

  resources :users
  
  resources :products do
    get :who_bought, on: :member
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store', via: :all
  end
end

app/views/layouts/_header.html.erb
<div id="banner">
   <%= image_tag "logo.png", alt: "Logo"%>
   <%= @page_title || t('.title') %>
</div>
<!--
<nav class="navbar navbar-default">
   <div class="container-fluid">
      <div class="navbar-header">
         <a class="navbar-brand" href="#">Pragmatic Bookshelf</a>
      </div>
      <div>
         <ul class="nav navbar-nav">
            <li><%= link_to "Home",     '#', class: "active" %></li>
            <li><%= link_to "Questions",  '#' %></li>
            <li><%= link_to "News",     '#' %></li>
            <li><%= link_to "Contact",    '#' %></li>
         </ul>
      </div>
   </div>
</nav>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Pragprog Books Online Store</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
   </head>
   <!--Load controller specific stylesheets -->
   <body class="container <%= controller.controller_name%>">
      
      <div id="banner">
         <%= form_tag store_path, class: 'locale' do %>
            <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s),
            onchange: 'this.form.submit()' %>
            <%= submit_tag 'submit' %>
            <%= javascript_tag "$('.locale input').hide()" %>
         <% end %>
         <%= image_tag "logo.png", alt: "Logo"%>
         <%= @page_title || t('.title') %>
      </div>

      <div id="columns">
         <div id="side">
            <% if @cart %>
               <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
                  <%= render @cart %>
               <% end %>
            <% end %>
            <ul>
               <li><%= link_to t('.home'),         '#' %></li>
               <li><%= link_to t('.questions'),    '#' %></li>
               <li><%= link_to t('.news'),         '#' %></li>
               <li><%= link_to t('.contact'),      '#' %></li>
            </ul>
           

            <% if session[:user_id] %>
               <ul>
                  <li><%= link_to 'Orders',     orders_path %></li>
                  <li><%= link_to 'Products',   products_path %></li>
                  <li><%= link_to 'Users',      users_path %></li>
               </ul>
               <%= button_to 'Logout', logout_path, method: :delete, class: "btn btn-primary" %>
            <% end %>
         </div>
      </div>
      <div id="main">
         <%= yield %>   
      </div>
   </body>
</html>